
create_table_per_user = '''
		CREATE TABLE WEB_URL(
		ID INTEGER PRIMARY KEY AUTOINCREMENT,
		URL TEXT ,
		S_URL TEXT ,
		TAG TEXT ,
		COUNTER INTEGER DEFAULT 0,
		CHROME INTEGER DEFAULT 0, 
		FIREFOX INTEGER DEFAULT 0, 
		SAFARI INTEGER DEFAULT 0, 
		OTHER_BROWSER INTEGER DEFAULT 0, 
		ANDROID INTEGER DEFAULT 0, 
		IOS INTEGER DEFAULT 0, 
		WINDOWS INTEGER DEFAULT 0, 
		LINUX INTEGER DEFAULT 0, 
		MAC INTEGER DEFAULT 0, 
		OTHER_PLATFORM INTEGER DEFAULT 0
		);
		'''

mysql_table = '''
		CREATE TABLE WEB_URL(
		ID INT AUTO_INCREMENT,
		URL VARCHAR(512),
		S_URL VARCHAR(80), 
		TAG VARCHAR(80),
		COUNTER INT DEFAULT 0,
		CHROME INT DEFAULT 0,
		FIREFOX INT DEFAULT 0,
		SAFARI INT DEFAULT 0,
		OTHER_BROWSER INT DEFAULT 0,
		ANDROID INT DEFAULT 0,
		IOS INT DEFAULT 0, 
		WINDOWS INT DEFAULT 0,
		LINUX INT DEFAULT 0,
		MAC INT DEFAULT 0,
		OTHER_PLATFORM INT DEFAULT 0 , 
		PRIMARY KEY(ID));
		'''

''' User Login SQL Table '''
# user_table = '''
# 		CREATE TABLE USER_SHORTY(
# 		ID INTEGER PRIMARY KEY AUTOINCREMENT,
# 		EMAIL TEXT ,
# 		NAME TEXT,
# 		ACTIVE BOOLEAN DEFAULT 0,
# 		TOKENS TEXT,
# 		CREATED_AT DATETIME, 
# 		);
# 		'''
